#!/usr/bin/env python

Import("env")
Import("env_modules")

env_qoa = env_modules.Clone()

thirdparty_dir = "./thirdparty"

# Treat qoa.h as system header to avoid raising warnings. Not supported on MSVC.
if not env.msvc:
    env_qoa.Append(CPPFLAGS=["-isystem", Dir(thirdparty_dir).path])
else:
    env_qoa.Prepend(CPPPATH=[thirdparty_dir])

# Godot source files
env_qoa.add_source_files(env.modules_sources, "*.cpp")
